<a href="https://colab.research.google.com/github/ashishkumarblog6783-code/numpy/blob/main/4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

indexing



In [2]:
import numpy as np
var=np.array([4,6,9])
print(var[1])
print(var[-3])

6
4


In [10]:
var1=np.array([[4,5,7],[6,7,4]])
print(var)
print(var.ndim)
print(var1[0,2])

[4 6 9]
1
7


slicing

In [15]:
import numpy as np
var=np.array([1,2,3,4,5,6,7])
print(var)
print()
print(var[2:5])
print(var[::])
print(var[1:5:2])

[1 2 3 4 5 6 7]

[3 4 5]
[1 2 3 4 5 6 7]
[2 4]


iteration


In [18]:
import numpy as np
var=np.array([1,2,4,5,6,7,9])
for i in var:
  print(i)
# The inner loop 'for l in k:' is not needed for a 1D array as 'k' itself is an element.
# If you intend to iterate over elements of a multi-dimensional array, you would need to adjust the array structure or indexing.
# For this 1D array, the first loop 'for i in var:' already achieves iteration over elements.

1
2
4
5
6
7
9


In [20]:
var=np.array([[[3,4,5,7],[4,1,1,6]]])
for i in np.nditer(var):
  print(i)

3
4
5
7
4
1
1
6


In [22]:
var=np.array([[[3,4,5,7],[4,1,1,6]]])
for i,d in np.ndenumerate(var):
  print(i,d)

(0, 0, 0) 3
(0, 0, 1) 4
(0, 0, 2) 5
(0, 0, 3) 7
(0, 1, 0) 4
(0, 1, 1) 1
(0, 1, 2) 1
(0, 1, 3) 6


copy vs view


In [23]:
import numpy as np
var=np.array([1,2,3,4])
co=var.copy()
print(var)
print(co)

[1 2 3 4]
[1 2 3 4]


In [25]:
x=np.array([2,4,6,8,9,0])
vi=x.view()
print(x)
print(vi)

[2 4 6 8 9 0]
[2 4 6 8 9 0]


join array


In [26]:
var=np.array([2,4,5,7])
var1=np.array([3,5,6,7])
ar=np.concatenate((var,var1))
print(ar)

[2 4 5 7 3 5 6 7]


In [27]:
v=np.array([[1,2],[3,4]])
b=np.array([[3,1],[4,4]])
ar=np.concatenate((v,b),axis=1)
print(ar)

[[1 2 3 1]
 [3 4 4 4]]


In [30]:
v=np.array([1,2,3,4])
b=np.array([3,1,4,4])
ar=np.stack((v,b),axis=1)
ar1=np.hstack((v,b))  #row
ar2=np.vstack((v,b))  #column
ar3=np.dstack((v,b))  #height
print(ar)
print(ar1)
print(ar2)
print(ar3)
#

[[1 3]
 [2 1]
 [3 4]
 [4 4]]
[1 2 3 4 3 1 4 4]
[[1 2 3 4]
 [3 1 4 4]]
[[[1 3]
  [2 1]
  [3 4]
  [4 4]]]


In [2]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)
ar=np.array_split(var,2)
print(ar)

[1 2 3 4 5]
[array([1, 2, 3]), array([4, 5])]


In [6]:
import numpy as np
var=np.array([[1,2],[3,4],[3,5]]) # Fixed the inhomogeneous shape
print(var)
ar=np.array_split(var,3)
print(ar)

[[1 2]
 [3 4]
 [3 5]]
[array([[1, 2]]), array([[3, 4]]), array([[3, 5]])]


In [7]:
var=np.array([1,2,3,4,5,6])
x=np.where(var==2)
print(x)

(array([1]),)


In [8]:
var=np.array([1,2,3,4,5,6])
x=np.where(var/2==0)
print(x)

(array([], dtype=int64),)


In [9]:
var=np.array([1,2,3,4,5,6])
x=np.where(var//3==0)
print(x)

(array([0, 1]),)


sort


In [10]:
var=np.array([1,9,0,11,2,3,4,5,6])
x=np.sort(var)
print(x)

[ 0  1  2  3  4  5  6  9 11]


In [11]:
var=np.array(["a","n","w","h","l","o","p"])
x=np.sort(var)
print(x)

['a' 'h' 'l' 'n' 'o' 'p' 'w']


filter

In [16]:
var=np.array([1,2,3,4])
x=[True,False,True,False]
new=var[x]
print(new)

[1 3]


In [17]:
v=np.array([1,2,3,4,5,6])
np.random.shuffle(v)
print(v)

[4 5 1 3 6 2]


In [19]:
var=np.array([1,2,3,4,5,6,7,7,2,3,3,3,])
x=np.unique(var,return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6]))


In [21]:
var=np.array([1,2,3,4,5,6,7,7,2,3,3,3,])
x=np.resize(var,(3,2))
print(x.flatten())

[1 2 3 4 5 6]


In [23]:
var=np.array([[1,2],[4,5]])
x=np.resize(var,(3,2))
print(x.flatten())

[1 2 4 5 1 2]


In [29]:
v=np.array([2,4,6,7])
print(v)
x=np.insert(var,2,5)
print(x)

[2 4 6 7]
[1 2 5 4 5]


In [30]:
v=np.array([2,4,6,7])
print(v)
x=np.insert(var,2,5,axis=1)
print(x)

[2 4 6 7]
[[1 2 5]
 [4 5 5]]
