<a href="https://colab.research.google.com/github/ashishkumarblog6783-code/numpy/blob/main/python2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
var=np.array([2,3,4,5,6,7])
print(np.min(var),np.argmin(var))
print(np.max(var),np.argmax(var))

2 0
7 5


In [6]:
var=np.array([[2,5,7,9],[7,4,0,9]])
print(np.min(var,axis=1))

[2 0]


In [7]:
var=np.array([4,7,0])
print(np.sin(var))
print(np.cos(var))


[-0.7568025  0.6569866  0.       ]
[-0.65364362  0.75390225  1.        ]


In [11]:
var=np.array([7,9,33])
print(np.cumsum(var))

[ 7 16 49]


In [14]:
var=np.array([[1,5],[8,0]])
print(var)
print(var.shape)
print(var.reshape)

[[1 5]
 [8 0]]
(2, 2)
<built-in method reshape of numpy.ndarray object at 0x7f3b9ccf3330>


In [27]:
import numpy as np
var=np.array([[5,9,7,7,9,0,6,0,0,0]])
x=var.reshape(2,5)
print(x)

[[5 9 7 7 9]
 [0 6 0 0 0]]
